service: flaskapi-aws-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1

layers:
  fastApi:
    path: fastApi_layer
    name: fastApi
    description: lambda layer for fastapi related dependencies
    compatibleRuntimes:
      - python3.9
    retain: false  

functions:
  hello:
    handler: handler.hello
    layers:
        - { Ref: FastApiLambdaLayer }

