on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: dev-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: -c "cd ../flask-api-lambda && serverless deploy"
        entrypoint: /bin/sh

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

